// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Model_BD.DAL.Models;

public partial class spamanagementContext : DbContext
{
    public spamanagementContext(DbContextOptions<spamanagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RoleMaster> RoleMasters { get; set; }

    public virtual DbSet<TaskList> TaskLists { get; set; }

    public virtual DbSet<TaskStatusMaster> TaskStatusMasters { get; set; }

    public virtual DbSet<UserDetail> UserDetails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RoleMaster>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleMast__3214EC2766DB4E3C");

            entity.ToTable("RoleMaster");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Label).HasMaxLength(150);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(150);
        });

        modelBuilder.Entity<TaskList>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskList__3214EC274D873C61");

            entity.ToTable("TaskList");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdvanceReceived).HasMaxLength(15);
            entity.Property(e => e.AgentName).HasMaxLength(150);
            entity.Property(e => e.AmountFixed).HasMaxLength(15);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DateAndTime).HasColumnType("datetime");
            entity.Property(e => e.Duration).HasMaxLength(10);
            entity.Property(e => e.GuestFirstName).HasMaxLength(150);
            entity.Property(e => e.GuestOccupation).HasMaxLength(150);
            entity.Property(e => e.GuestPhoneNo).HasMaxLength(20);
            entity.Property(e => e.GuestPreference).HasMaxLength(150);
            entity.Property(e => e.GuestRating).HasMaxLength(2);
            entity.Property(e => e.Incash).HasMaxLength(10);
            entity.Property(e => e.Location).HasMaxLength(150);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NoOfServices).HasMaxLength(150);
            entity.Property(e => e.Online).HasMaxLength(10);
            entity.Property(e => e.ReferenceNo).HasMaxLength(30);
            entity.Property(e => e.StuffType).HasMaxLength(150);
            entity.Property(e => e.TravelExpense).HasMaxLength(15);
            entity.Property(e => e.TypeOfService).HasMaxLength(100);
            entity.Property(e => e.YourProfit).HasMaxLength(15);

            entity.HasOne(d => d.Status).WithMany(p => p.TaskLists)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__TaskList__Status__412EB0B6");
        });

        modelBuilder.Entity<TaskStatusMaster>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskStat__3214EC27D4B7386C");

            entity.ToTable("TaskStatusMaster");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");
            entity.Property(e => e.Label).HasMaxLength(60);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(60);
        });

        modelBuilder.Entity<UserDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserDeta__3214EC27B3CA793C");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(70);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.MobileNo).HasMaxLength(20);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(500);

            entity.HasOne(d => d.Role).WithMany(p => p.UserDetails)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__UserDetai__RoleI__3D5E1FD2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}